services:
  - type: web
    name: edusphere-api
    env: node
    region: singapore
    plan: free
    buildCommand: npm install && npx prisma generate
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001
      - key: JWT_SECRET
        generateValue: true
      - key: COOKIE_SECRET
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: ALLOWED_ORIGINS
        value: https://edusphere-school.netlify.app
      - key: RATE_LIMIT_ENABLED
        value: false
