import 'dart:convert';
import 'package:http/http.dart' as http;

void main() async {
  final baseUrl = 'https://edusphere-erp-frontend.onrender.com/api/v1';

  print('1. Logging in as teacher...');
  final loginRes = await http.post(
    Uri.parse('$baseUrl/auth/login'),
    headers: {'Content-Type': 'application/json'},
    body: jsonEncode({
      'email': 'teacher1@edusphere.com',
      'password': 'Password@123',
    }),
  );

  final loginData = jsonDecode(loginRes.body);
  final token = loginData['token'];

  final headers = {
    'Content-Type': 'application/json',
    'Authorization': 'Bearer $token',
  };

  print('\n2. Fetching Classes...');
  final classesRes = await http.get(Uri.parse('$baseUrl/academic/classes'), headers: headers);
  final classes = jsonDecode(classesRes.body)['classes'] as List;
  final classId = classes.first['id'];

  print('\n3. Fetching Subjects...');
  final subjectsRes = await http.get(Uri.parse('$baseUrl/academic/subjects?classId=$classId'), headers: headers);
  final subjects = jsonDecode(subjectsRes.body)['subjects'] as List;
  final subjectId = subjects.first['id'];

  print('\n4. Creating/Saving Assignment in database...');
  final payload = {
    'title': 'Test AI Assignment',
    'description': '# Test AI Assignment\nThis is generated by AI.',
    'dueDate': DateTime.now().add(const Duration(days: 7)).toUtc().toIso8601String(),
    'subjectId': subjectId,
    'classId': classId,
    'aiPdfPath': '/uploads/assignments/references/assignment_db293be3-0ef4-4b53-ae3c-44b256d25a3a.pdf',
  };

  final saveRes = await http.post(
    Uri.parse('$baseUrl/assignments'),
    headers: headers,
    body: jsonEncode(payload),
  );

  if (saveRes.statusCode == 201) {
    print('✅ Assignment saved successfully in database!');
    print('Response body: ${saveRes.body}');
  } else {
    print('❌ Failed to save assignment: ${saveRes.body}');
  }
}
